-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 23:19:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8mb3 ;
USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `supervisor` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`email`, `username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `user`.`generi_musicali_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`generi_musicali_user` (
  `Pop` TINYINT NULL DEFAULT NULL,
  `Indie` TINYINT NULL DEFAULT NULL,
  `Classic` TINYINT NULL DEFAULT NULL,
  `Rock` TINYINT NULL DEFAULT NULL,
  `Electronic` TINYINT NULL DEFAULT NULL,
  `House` TINYINT NULL DEFAULT NULL,
  `HipHop` TINYINT NULL DEFAULT NULL,
  `Jazz` TINYINT NULL DEFAULT NULL,
  `Acoustic` TINYINT NULL DEFAULT NULL,
  `REB` TINYINT NULL DEFAULT NULL,
  `Country` TINYINT NULL DEFAULT NULL,
  `Alternative` TINYINT NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  INDEX `fk_generi_musicali_user_user1_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_generi_musicali_user_user1`
    FOREIGN KEY (`email`)
    REFERENCES `user`.`user` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `user`.`notifiche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`notifiche` (
  `body` VARCHAR(512) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_notifiche_user1` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_notifiche_user1`
    FOREIGN KEY (`email`)
    REFERENCES `user`.`user` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `user`.`playlist_utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`playlist_utente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `namePlaylist` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `link` VARCHAR(512) NOT NULL,
  `approved` INT NULL DEFAULT '0',
  `slider1` DOUBLE NULL DEFAULT NULL,
  `slider2` DOUBLE NULL DEFAULT NULL,
  `slider3` DOUBLE NULL DEFAULT NULL,
  `slider4` DOUBLE NULL DEFAULT NULL,
  `Pop` TINYINT NULL DEFAULT NULL,
  `Indie` TINYINT NULL DEFAULT NULL,
  `Classic` TINYINT NULL DEFAULT NULL,
  `Rock` TINYINT NULL DEFAULT NULL,
  `Electronic` TINYINT NULL DEFAULT NULL,
  `House` TINYINT NULL DEFAULT NULL,
  `HipHop` TINYINT NULL DEFAULT NULL,
  `Jazz` TINYINT NULL DEFAULT NULL,
  `Acoustic` TINYINT NULL DEFAULT NULL,
  `REB` TINYINT NULL DEFAULT NULL,
  `Country` TINYINT NULL DEFAULT NULL,
  `Alternative` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `namePlaylist`, `link`),
  INDEX `fk_Playlist_Utente_user1_idx` (`email` ASC) VISIBLE,
  INDEX `playlist_utente_user_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `playlist_utente_user`
    FOREIGN KEY (`username`)
    REFERENCES `user`.`user` (`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 170
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
